-- ============================================================================
-- V13 - Melee catalog (generated from src/main/resources/catalog/*.json)
-- ============================================================================
-- Adds the Unity Melee catalog on top of the Vandal set from V12: upserts the
-- Melee skins as active and adds the melee_case with its drop pool. Does not
-- touch the existing Vandal skins or cases. Catalog tables only; no player-owned
-- tables are referenced.
-- ============================================================================

-- Melee skins (168). Upsert by primary key id.
INSERT INTO skins (id, display_name, weapon, rarity, vp_value, image_ref, active) VALUES
    ('skin_melee_power_fist', 'Power Fist', 'Melee', 'Exclusive', 5950, 'Art/Skins/Melee/power_fist', TRUE),
    ('skin_melee_araxys_bio_atomizers', 'Araxys Bio-Atomizers', 'Melee', 'Exclusive', 5350, 'Art/Skins/Melee/araxys_bio_atomizers', TRUE),
    ('skin_melee_waveform', 'Waveform', 'Melee', 'Exclusive', 5350, 'Art/Skins/Melee/waveform', TRUE),
    ('skin_melee_phaseguard_splitter', 'Phaseguard Splitter', 'Melee', 'Exclusive', 5350, 'Art/Skins/Melee/phaseguard_splitter', TRUE),
    ('skin_melee_nocturnum_scythe', 'Nocturnum Scythe', 'Melee', 'Exclusive', 5350, 'Art/Skins/Melee/nocturnum_scythe', TRUE),
    ('skin_melee_ex_o_edge', 'EX.O Edge', 'Melee', 'Exclusive', 5350, 'Art/Skins/Melee/ex_o_edge', TRUE),
    ('skin_melee_kuronami_no_yaiba', 'Kuronami no Yaiba', 'Melee', 'Exclusive', 5350, 'Art/Skins/Melee/kuronami_no_yaiba', TRUE),
    ('skin_melee_kuronami_naru_kami', 'Kuronami Naru-Kami', 'Melee', 'Exclusive', 5350, 'Art/Skins/Melee/kuronami_naru_kami', TRUE),
    ('skin_melee_onimaru_kunitsuna', 'Onimaru Kunitsuna', 'Melee', 'Exclusive', 5350, 'Art/Skins/Melee/onimaru_kunitsuna', TRUE),
    ('skin_melee_reaver_butterfly', 'Reaver Butterfly', 'Melee', 'Exclusive', 5350, 'Art/Skins/Melee/reaver_butterfly', TRUE),
    ('skin_melee_cyrax_fanblade', 'CYRAX Fanblade', 'Melee', 'Exclusive', 5350, 'Art/Skins/Melee/cyrax_fanblade', TRUE),
    ('skin_melee_kogitsune', 'Kogitsune', 'Melee', 'Exclusive', 5350, 'Art/Skins/Melee/kogitsune', TRUE),
    ('skin_melee_elderflame_dagger', 'Elderflame Dagger', 'Melee', 'Exclusive', 4950, 'Art/Skins/Melee/elderflame_dagger', TRUE),
    ('skin_melee_ora_by_onetap', 'ORA by OneTap', 'Melee', 'Exclusive', 4950, 'Art/Skins/Melee/ora_by_onetap', TRUE),
    ('skin_melee_personal_administrative_melee_unit', 'Personal Administrative Melee Unit', 'Melee', 'Exclusive', 4950, 'Art/Skins/Melee/personal_administrative_melee_unit', TRUE),
    ('skin_melee_evori_s_spellcaster', 'Evori''s Spellcaster', 'Melee', 'Exclusive', 4950, 'Art/Skins/Melee/evori_s_spellcaster', TRUE),
    ('skin_melee_rgx_11z_pro_blade', 'RGX 11z Pro Blade', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/rgx_11z_pro_blade', TRUE),
    ('skin_melee_rgx_11z_pro_firefly', 'RGX 11z Pro Firefly', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/rgx_11z_pro_firefly', TRUE),
    ('skin_melee_rgx_11z_pro_karambit', 'RGX 11z Pro Karambit', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/rgx_11z_pro_karambit', TRUE),
    ('skin_melee_divergence_staff', 'Divergence Staff', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/divergence_staff', TRUE),
    ('skin_melee_araxys_bio_harvester', 'Araxys Bio Harvester', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/araxys_bio_harvester', TRUE),
    ('skin_melee_bolt', 'Bolt', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/bolt', TRUE),
    ('skin_melee_doombringer_battleaxe', 'Doombringer Battleaxe', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/doombringer_battleaxe', TRUE),
    ('skin_melee_glitchpop_dagger', 'Glitchpop Dagger', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/glitchpop_dagger', TRUE),
    ('skin_melee_glitchpop_axe', 'Glitchpop Axe', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/glitchpop_axe', TRUE),
    ('skin_melee_terminus_a_quo', 'Terminus A Quo', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/terminus_a_quo', TRUE),
    ('skin_melee_blade_of_chaos', 'Blade of Chaos', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/blade_of_chaos', TRUE),
    ('skin_melee_flail_of_chaos', 'Flail of Chaos', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/flail_of_chaos', TRUE),
    ('skin_melee_blades_of_imperium', 'Blades of Imperium', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/blades_of_imperium', TRUE),
    ('skin_melee_singularity', 'Singularity', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/singularity', TRUE),
    ('skin_melee_singularity_butterfly', 'Singularity Butterfly', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/singularity_butterfly', TRUE),
    ('skin_melee_dolmir_s_judgement', 'Dolmir''s Judgement', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/dolmir_s_judgement', TRUE),
    ('skin_melee_neo_frontier_axe', 'Neo Frontier Axe', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/neo_frontier_axe', TRUE),
    ('skin_melee_bubblegum_deathwish_chainsaw', 'Bubblegum Deathwish Chainsaw', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/bubblegum_deathwish_chainsaw', TRUE),
    ('skin_melee_blades_of_primordia', 'Blades of Primordia', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/blades_of_primordia', TRUE),
    ('skin_melee_xerfang', 'XERØFANG', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/xerfang', TRUE),
    ('skin_melee_broken_blade_of_the_ruined_king', 'Broken Blade of the Ruined King', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/broken_blade_of_the_ruined_king', TRUE),
    ('skin_melee_magepunk_sparkswitch', 'Magepunk Sparkswitch', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/magepunk_sparkswitch', TRUE),
    ('skin_melee_ruyi_staff', 'Ruyi Staff', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/ruyi_staff', TRUE),
    ('skin_melee_overdrive_blade', 'Overdrive Blade', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/overdrive_blade', TRUE),
    ('skin_melee_ion_karambit', 'Ion Karambit', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/ion_karambit', TRUE),
    ('skin_melee_rogue_push_daggers', 'Rogue Push Daggers', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/rogue_push_daggers', TRUE),
    ('skin_melee_blackthorn_blades', 'Blackthorn Blades', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/blackthorn_blades', TRUE),
    ('skin_melee_holoflare', 'Holoflare', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/holoflare', TRUE),
    ('skin_melee_helix_daggers', 'Helix Daggers', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/helix_daggers', TRUE),
    ('skin_melee_relic_of_the_sentinel', 'Relic of the Sentinel', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/relic_of_the_sentinel', TRUE),
    ('skin_melee_relic_stone_daggers', 'Relic Stone Daggers', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/relic_stone_daggers', TRUE),
    ('skin_melee_reaver_karambit', 'Reaver Karambit', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/reaver_karambit', TRUE),
    ('skin_melee_eternal_sovereign', 'Eternal Sovereign', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/eternal_sovereign', TRUE),
    ('skin_melee_mystbloom_kunai', 'Mystbloom Kunai', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/mystbloom_kunai', TRUE),
    ('skin_melee_mystbloom_fanblade', 'Mystbloom Fanblade', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/mystbloom_fanblade', TRUE),
    ('skin_melee_blastx_polymer_knifetech_coated', 'BlastX Polymer KnifeTech Coated', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/blastx_polymer_knifetech_coated', TRUE),
    ('skin_melee_splashx_gloves', 'SplashX Gloves', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/splashx_gloves', TRUE),
    ('skin_melee_xenohunter', 'Xenohunter', 'Melee', 'Exclusive', 3550, 'Art/Skins/Melee/xenohunter', TRUE),
    ('skin_melee_valorant_go_vol_1', 'VALORANT GO! Vol. 1', 'Melee', 'Exclusive', 3550, 'Art/Skins/Melee/valorant_go_vol_1', TRUE),
    ('skin_melee_yoru_s_stylish_butterfly_comb', 'Yoru''s Stylish Butterfly Comb', 'Melee', 'Exclusive', 3550, 'Art/Skins/Melee/yoru_s_stylish_butterfly_comb', TRUE),
    ('skin_melee_neptune_anchor', 'Neptune Anchor', 'Melee', 'Exclusive', 3550, 'Art/Skins/Melee/neptune_anchor', TRUE),
    ('skin_melee_neptune_hook', 'Neptune Hook', 'Melee', 'Exclusive', 3550, 'Art/Skins/Melee/neptune_hook', TRUE),
    ('skin_melee_gaia_s_wrath', 'Gaia''s Wrath', 'Melee', 'Exclusive', 3550, 'Art/Skins/Melee/gaia_s_wrath', TRUE),
    ('skin_melee_gaia_s_fury', 'Gaia''s Fury', 'Melee', 'Exclusive', 3550, 'Art/Skins/Melee/gaia_s_fury', TRUE),
    ('skin_melee_origin_crescent_blade', 'Origin Crescent Blade', 'Melee', 'Exclusive', 3550, 'Art/Skins/Melee/origin_crescent_blade', TRUE),
    ('skin_melee_radiant_crisis_001_baseball_bat', 'Radiant Crisis 001 Baseball Bat', 'Melee', 'Exclusive', 3550, 'Art/Skins/Melee/radiant_crisis_001_baseball_bat', TRUE),
    ('skin_melee_nebula', 'Nebula', 'Melee', 'Exclusive', 3550, 'Art/Skins/Melee/nebula', TRUE),
    ('skin_melee_hack', 'Hack', 'Melee', 'Exclusive', 3550, 'Art/Skins/Melee/hack', TRUE),
    ('skin_melee_forsaken_ritual_blade', 'Forsaken Ritual Blade', 'Melee', 'Exclusive', 3550, 'Art/Skins/Melee/forsaken_ritual_blade', TRUE),
    ('skin_melee_soulstrife_scythe', 'Soulstrife Scythe', 'Melee', 'Exclusive', 3550, 'Art/Skins/Melee/soulstrife_scythe', TRUE),
    ('skin_melee_prime_axe', 'Prime Axe', 'Melee', 'Exclusive', 3550, 'Art/Skins/Melee/prime_axe', TRUE),
    ('skin_melee_prime_2_0_karambit', 'Prime//2.0 Karambit', 'Melee', 'Exclusive', 3550, 'Art/Skins/Melee/prime_2_0_karambit', TRUE),
    ('skin_melee_black_market_butterfly', 'Black.Market Butterfly', 'Melee', 'Exclusive', 3550, 'Art/Skins/Melee/black_market_butterfly', TRUE),
    ('skin_melee_blade_of_aemondir', 'Blade of Aemondir', 'Melee', 'Exclusive', 3550, 'Art/Skins/Melee/blade_of_aemondir', TRUE),
    ('skin_melee_solarstride_flamethrower', 'Solarstride Flamethrower', 'Melee', 'Exclusive', 3550, 'Art/Skins/Melee/solarstride_flamethrower', TRUE),
    ('skin_melee_celestial_fan', 'Celestial Fan', 'Melee', 'Exclusive', 3550, 'Art/Skins/Melee/celestial_fan', TRUE),
    ('skin_melee_magepunk_electroblade', 'Magepunk Electroblade', 'Melee', 'Exclusive', 3550, 'Art/Skins/Melee/magepunk_electroblade', TRUE),
    ('skin_melee_magepunk_shock_gauntlet', 'Magepunk Shock Gauntlet', 'Melee', 'Exclusive', 3550, 'Art/Skins/Melee/magepunk_shock_gauntlet', TRUE),
    ('skin_melee_spline_dagger', 'Spline Dagger', 'Melee', 'Exclusive', 3550, 'Art/Skins/Melee/spline_dagger', TRUE),
    ('skin_melee_minima_karambit', 'Minima Karambit', 'Melee', 'Exclusive', 3550, 'Art/Skins/Melee/minima_karambit', TRUE),
    ('skin_melee_crimsonbeast_hammer', 'Crimsonbeast Hammer', 'Melee', 'Exclusive', 3550, 'Art/Skins/Melee/crimsonbeast_hammer', TRUE),
    ('skin_melee_ion_energy_sword', 'Ion Energy Sword', 'Melee', 'Exclusive', 3550, 'Art/Skins/Melee/ion_energy_sword', TRUE),
    ('skin_melee_oni_claw', 'Oni Claw', 'Melee', 'Exclusive', 3550, 'Art/Skins/Melee/oni_claw', TRUE),
    ('skin_melee_cryostasis_impact_drill', 'Cryostasis Impact Drill', 'Melee', 'Exclusive', 3550, 'Art/Skins/Melee/cryostasis_impact_drill', TRUE),
    ('skin_melee_luna_s_descent', 'Luna''s Descent', 'Melee', 'Exclusive', 3550, 'Art/Skins/Melee/luna_s_descent', TRUE),
    ('skin_melee_gravitational_uranium_neuroblaster_baton', 'Gravitational Uranium Neuroblaster Baton', 'Melee', 'Exclusive', 3550, 'Art/Skins/Melee/gravitational_uranium_neuroblaster_baton', TRUE),
    ('skin_melee_reaver', 'Reaver', 'Melee', 'Exclusive', 3550, 'Art/Skins/Melee/reaver', TRUE),
    ('skin_melee_sovereign_sword', 'Sovereign Sword', 'Melee', 'Exclusive', 3550, 'Art/Skins/Melee/sovereign_sword', TRUE),
    ('skin_melee_prosperity', 'Prosperity', 'Melee', 'Exclusive', 3550, 'Art/Skins/Melee/prosperity', TRUE),
    ('skin_melee_recon_balisong', 'Recon Balisong', 'Melee', 'Exclusive', 3550, 'Art/Skins/Melee/recon_balisong', TRUE),
    ('skin_melee_wonderstallion_hammer', 'Wonderstallion Hammer', 'Melee', 'Exclusive', 3550, 'Art/Skins/Melee/wonderstallion_hammer', TRUE),
    ('skin_melee_ego', 'Ego', 'Melee', 'Exclusive', 3550, 'Art/Skins/Melee/ego', TRUE),
    ('skin_melee_altitude_knuckle', 'Altitude Knuckle', 'Melee', 'Exclusive', 2550, 'Art/Skins/Melee/altitude_knuckle', TRUE),
    ('skin_melee_valorant_go_vol_3_dagger', 'VALORANT GO! Vol. 3 Dagger', 'Melee', 'Exclusive', 2550, 'Art/Skins/Melee/valorant_go_vol_3_dagger', TRUE),
    ('skin_melee_mk_vii_liberty_combat', 'MK.VII Liberty Combat', 'Melee', 'Exclusive', 2550, 'Art/Skins/Melee/mk_vii_liberty_combat', TRUE),
    ('skin_melee_aperture_stiletto', 'Aperture Stiletto', 'Melee', 'Exclusive', 2550, 'Art/Skins/Melee/aperture_stiletto', TRUE),
    ('skin_melee_emberclad_hammer', 'Emberclad Hammer', 'Melee', 'Exclusive', 2550, 'Art/Skins/Melee/emberclad_hammer', TRUE),
    ('skin_melee_caeruleus', 'Caeruleus', 'Melee', 'Exclusive', 2550, 'Art/Skins/Melee/caeruleus', TRUE),
    ('skin_melee_nanomight_knuckles', 'Nanomight Knuckles', 'Melee', 'Exclusive', 2550, 'Art/Skins/Melee/nanomight_knuckles', TRUE),
    ('skin_melee_blade_of_serket', 'Blade of Serket', 'Melee', 'Exclusive', 2550, 'Art/Skins/Melee/blade_of_serket', TRUE),
    ('skin_melee_chromedek_gauntlet', 'Chromedek Gauntlet', 'Melee', 'Exclusive', 2550, 'Art/Skins/Melee/chromedek_gauntlet', TRUE),
    ('skin_melee_jellybeam_sugarslice', 'Jellybeam Sugarslice', 'Melee', 'Exclusive', 2550, 'Art/Skins/Melee/jellybeam_sugarslice', TRUE),
    ('skin_melee_prism', 'Prism', 'Melee', 'Exclusive', 2550, 'Art/Skins/Melee/prism', TRUE),
    ('skin_melee_equilibrium', 'Equilibrium', 'Melee', 'Exclusive', 2550, 'Art/Skins/Melee/equilibrium', TRUE),
    ('skin_melee_catrina', 'Catrina', 'Melee', 'Exclusive', 2550, 'Art/Skins/Melee/catrina', TRUE),
    ('skin_melee_combat_crafts_axe', 'Combat Crafts Axe', 'Melee', 'Exclusive', 2550, 'Art/Skins/Melee/combat_crafts_axe', TRUE),
    ('skin_melee_silkleaf_fan', 'SilkLeaf Fan', 'Melee', 'Exclusive', 2550, 'Art/Skins/Melee/silkleaf_fan', TRUE),
    ('skin_melee_orion_sword', 'Orion Sword', 'Melee', 'Exclusive', 2550, 'Art/Skins/Melee/orion_sword', TRUE),
    ('skin_melee_snowfall_wand', 'Snowfall Wand', 'Melee', 'Exclusive', 2550, 'Art/Skins/Melee/snowfall_wand', TRUE),
    ('skin_melee_titanmail_mace', 'Titanmail Mace', 'Melee', 'Exclusive', 2550, 'Art/Skins/Melee/titanmail_mace', TRUE),
    ('skin_melee_hu_else', 'Hu Else', 'Melee', 'Exclusive', 2550, 'Art/Skins/Melee/hu_else', TRUE),
    ('skin_melee_no_limits_bat', 'NO LIMITS Bat', 'Melee', 'Exclusive', 2550, 'Art/Skins/Melee/no_limits_bat', TRUE),
    ('skin_melee_kaimana', 'Kaimana', 'Melee', 'Exclusive', 2550, 'Art/Skins/Melee/kaimana', TRUE),
    ('skin_melee_wasteland_crowbar', 'Wasteland Crowbar', 'Melee', 'Exclusive', 2550, 'Art/Skins/Melee/wasteland_crowbar', TRUE),
    ('skin_melee_winterwunderland_candy_cane', 'Winterwunderland Candy Cane', 'Melee', 'Exclusive', 2550, 'Art/Skins/Melee/winterwunderland_candy_cane', TRUE),
    ('skin_melee_intergrade_blade', 'Intergrade Blade', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/intergrade_blade', TRUE),
    ('skin_melee_smite', 'Smite', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/smite', TRUE),
    ('skin_melee_smite_hammer', 'Smite Hammer', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/smite_hammer', TRUE),
    ('skin_melee_daydreams_crowbar', 'Daydreams Crowbar', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/daydreams_crowbar', TRUE),
    ('skin_melee_luxe', 'Luxe', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/luxe', TRUE),
    ('skin_melee_switchback_ascender', 'Switchback Ascender', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/switchback_ascender', TRUE),
    ('skin_melee_reverie_sword', 'Reverie Sword', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/reverie_sword', TRUE),
    ('skin_melee_fortune_s_scepter', 'Fortune''s Scepter', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/fortune_s_scepter', TRUE),
    ('skin_melee_storm_maw_axe', 'Storm Maw Axe', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/storm_maw_axe', TRUE),
    ('skin_melee_task_force_809', 'Task Force 809', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/task_force_809', TRUE),
    ('skin_melee_champions_2021_karambit', 'Champions 2021 Karambit', 'Melee', 'Exclusive', 5350, 'Art/Skins/Melee/champions_2021_karambit', TRUE),
    ('skin_melee_champions_2022_butterfly', 'Champions 2022 Butterfly', 'Melee', 'Exclusive', 5350, 'Art/Skins/Melee/champions_2022_butterfly', TRUE),
    ('skin_melee_champions_2023_kunai', 'Champions 2023 Kunai', 'Melee', 'Exclusive', 5350, 'Art/Skins/Melee/champions_2023_kunai', TRUE),
    ('skin_melee_champions_2024_blade', 'Champions 2024 Blade', 'Melee', 'Exclusive', 5350, 'Art/Skins/Melee/champions_2024_blade', TRUE),
    ('skin_melee_champions_2025_butterfly', 'Champions 2025 Butterfly', 'Melee', 'Exclusive', 5350, 'Art/Skins/Melee/champions_2025_butterfly', TRUE),
    ('skin_melee_vct_2025_karambit', 'VCT 2025 Karambit', 'Melee', 'Exclusive', 5350, 'Art/Skins/Melee/vct_2025_karambit', TRUE),
    ('skin_melee_vct_2026_sigil', 'VCT 2026 Sigil', 'Melee', 'Exclusive', 5350, 'Art/Skins/Melee/vct_2026_sigil', TRUE),
    ('skin_melee_obsidiana', 'Obsidiana', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/obsidiana', TRUE),
    ('skin_melee_composite', 'Composite', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/composite', TRUE),
    ('skin_melee_atlas_cmd_baton', 'ATLAS // CMD Baton', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/atlas_cmd_baton', TRUE),
    ('skin_melee_overlay_dagger', 'Overlay Dagger', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/overlay_dagger', TRUE),
    ('skin_melee_striker', 'Striker', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/striker', TRUE),
    ('skin_melee_comet_sword', 'Comet Sword', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/comet_sword', TRUE),
    ('skin_melee_songsteel', 'Songsteel', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/songsteel', TRUE),
    ('skin_melee_vct_lock_in_misericordia', 'VCT LOCK//IN Misericórdia', 'Melee', 'Exclusive', 5350, 'Art/Skins/Melee/vct_lock_in_misericordia', TRUE),
    ('skin_melee_hivemind_sword', 'Hivemind Sword', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/hivemind_sword', TRUE),
    ('skin_melee_venturi', 'Venturi', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/venturi', TRUE),
    ('skin_melee_velocity_karambit', 'Velocity Karambit', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/velocity_karambit', TRUE),
    ('skin_melee_heart_splitter', 'Heart Splitter', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/heart_splitter', TRUE),
    ('skin_melee_interhelm_sword', 'Interhelm Sword', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/interhelm_sword', TRUE),
    ('skin_melee_ruin_dagger', 'Ruin Dagger', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/ruin_dagger', TRUE),
    ('skin_melee_sys', '.SYS', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/sys', TRUE),
    ('skin_melee_hieroscape_blades', 'Hieroscape Blades', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/hieroscape_blades', TRUE),
    ('skin_melee_bubble_pop_light_stick', 'Bubble Pop Light Stick', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/bubble_pop_light_stick', TRUE),
    ('skin_melee_outpost', 'Outpost', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/outpost', TRUE),
    ('skin_melee_guardrail_hammer', 'Guardrail Hammer', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/guardrail_hammer', TRUE),
    ('skin_melee_bound', 'Bound', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/bound', TRUE),
    ('skin_melee_prism_iii_axe', 'Prism III Axe', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/prism_iii_axe', TRUE),
    ('skin_melee_kingdom', 'Kingdom', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/kingdom', TRUE),
    ('skin_melee_k_tac_blade', 'K/TAC Blade', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/k_tac_blade', TRUE),
    ('skin_melee_iridian_thorn_blade', 'Iridian Thorn Blade', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/iridian_thorn_blade', TRUE),
    ('skin_melee_arcane_gauntlets', 'Arcane Gauntlets', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/arcane_gauntlets', TRUE),
    ('skin_melee_montage_axe', 'Montage Axe', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/montage_axe', TRUE),
    ('skin_melee_genesis_arc', 'Genesis Arc', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/genesis_arc', TRUE),
    ('skin_melee_artisan_foil', 'Artisan Foil', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/artisan_foil', TRUE),
    ('skin_melee_keys_to_elysium', 'Keys to Elysium', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/keys_to_elysium', TRUE),
    ('skin_melee_hi_dr0_baton', 'Hi-DR0 Baton', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/hi_dr0_baton', TRUE),
    ('skin_melee_shellspire_sword', 'Shellspire Sword', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/shellspire_sword', TRUE),
    ('skin_melee_transition', 'Transition', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/transition', TRUE),
    ('skin_melee_byteshift', 'Byteshift', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/byteshift', TRUE),
    ('skin_melee_torque_coiler', 'Torque Coiler', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/torque_coiler', TRUE),
    ('skin_melee_paceline_s_edge', 'Paceline''s Edge', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/paceline_s_edge', TRUE),
    ('skin_melee_tilde', 'Tilde', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/tilde', TRUE),
    ('skin_melee_sandswept_dagger', 'Sandswept Dagger', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/sandswept_dagger', TRUE),
    ('skin_melee_solarex_relic', 'Solarex Relic', 'Melee', 'Exclusive', 1750, 'Art/Skins/Melee/solarex_relic', TRUE),
    ('skin_melee_5_years_beta_remastered', '5 Years // Beta Remastered', 'Melee', 'Exclusive', 4350, 'Art/Skins/Melee/5_years_beta_remastered', TRUE),
    ('skin_melee_ignite_fan', 'Ignite Fan', 'Melee', 'Exclusive', 4950, 'Art/Skins/Melee/ignite_fan', TRUE)
ON CONFLICT (id) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    weapon       = EXCLUDED.weapon,
    rarity       = EXCLUDED.rarity,
    vp_value     = EXCLUDED.vp_value,
    image_ref    = EXCLUDED.image_ref,
    active       = EXCLUDED.active;

-- Melee case. Upsert by primary key id.
INSERT INTO case_definitions (id, display_name, price_vp, image_ref, active) VALUES
    ('melee_case', 'Melee Case', 2500, 'Art/Cases/Melee_Case', TRUE)
ON CONFLICT (id) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    price_vp     = EXCLUDED.price_vp,
    image_ref    = EXCLUDED.image_ref,
    active       = EXCLUDED.active;

-- Rebuild melee_case drop pool: drop its entries, then insert the current pool.
DELETE FROM case_entries WHERE case_id = 'melee_case';

-- Melee drop-pool entries (15).
INSERT INTO case_entries (id, case_id, skin_id, weight) VALUES
    (gen_random_uuid(), 'melee_case', 'skin_melee_task_force_809', 1),
    (gen_random_uuid(), 'melee_case', 'skin_melee_obsidiana', 1),
    (gen_random_uuid(), 'melee_case', 'skin_melee_composite', 1),
    (gen_random_uuid(), 'melee_case', 'skin_melee_atlas_cmd_baton', 1),
    (gen_random_uuid(), 'melee_case', 'skin_melee_overlay_dagger', 1),
    (gen_random_uuid(), 'melee_case', 'skin_melee_striker', 1),
    (gen_random_uuid(), 'melee_case', 'skin_melee_comet_sword', 1),
    (gen_random_uuid(), 'melee_case', 'skin_melee_songsteel', 1),
    (gen_random_uuid(), 'melee_case', 'skin_melee_hivemind_sword', 1),
    (gen_random_uuid(), 'melee_case', 'skin_melee_venturi', 1),
    (gen_random_uuid(), 'melee_case', 'skin_melee_velocity_karambit', 1),
    (gen_random_uuid(), 'melee_case', 'skin_melee_heart_splitter', 1),
    (gen_random_uuid(), 'melee_case', 'skin_melee_interhelm_sword', 1),
    (gen_random_uuid(), 'melee_case', 'skin_melee_ruin_dagger', 1),
    (gen_random_uuid(), 'melee_case', 'skin_melee_sys', 1);
