-- ValoCase backend - Phase 1 foundation migration.
--
-- This migration intentionally creates NO domain schema yet.
-- Account / Wallet / Inventory / Catalog / Case tables are deferred to later
-- steps per the accepted Phase 1 design.
--
-- It creates a single harmless bootstrap marker table purely to prove that
-- Flyway is wired correctly and that migrations run against valocase_db.
-- This table can be dropped in a later migration once real schema lands.
CREATE TABLE IF NOT EXISTS flyway_bootstrap_check (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note       VARCHAR(255) NOT NULL DEFAULT 'foundation ok',
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);
