#!/usr/bin/env python3
"""Generate the next Flyway catalog-sync migration from the Unity catalog.

Unity's skins.json and cases.json are the source of truth. This tool validates
them and emits src/main/resources/db/migration/V{next}__catalog_sync.sql, which
upserts skins and cases and rebuilds the drop pools of the cases it contains.
It never touches player data (inventory, wallets, transactions, history) and
never rewrites existing migrations.
"""

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
MIGRATION_DIR = REPO_ROOT / "src" / "main" / "resources" / "db" / "migration"

UNITY_CONFIG = Path(r"C:\Users\cenk_\ValoCase\Assets\_ValoCase\Resources\Config")
DEFAULT_SKINS = UNITY_CONFIG / "skins.json"
DEFAULT_CASES = UNITY_CONFIG / "cases.json"
DEFAULT_ART_CASES = Path(r"C:\Users\cenk_\ValoCase\Assets\_ValoCase\Resources\Art\Cases")

CASE_FIELDS = ("caseId", "displayName", "price", "resourceKey", "enabled", "manualDropPool")


def sql_str(value):
    return "'" + str(value).replace("'", "''") + "'"


def sql_bool(value):
    return "TRUE" if value else "FALSE"


def load_array(path, key):
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    if isinstance(data, list):
        return data
    if isinstance(data, dict) and isinstance(data.get(key), list):
        return data[key]
    raise ValueError(f"{path} must be a JSON array or an object with a '{key}' array")


def pool_skin_id(entry):
    if isinstance(entry, str):
        return entry, 1
    if isinstance(entry, dict) and entry.get("skinId"):
        weight = entry.get("weight", 1)
        weight = int(weight) if isinstance(weight, (int, float)) and weight > 0 else 1
        return entry["skinId"], weight
    raise ValueError(f"invalid drop pool entry: {entry!r}")


def validate(skins, cases, art_dir):
    errors = []
    warnings = []

    by_id = {}
    for s in skins:
        sid = s.get("skinId")
        if not sid:
            errors.append("a skin entry is missing skinId")
            continue
        if sid in by_id:
            errors.append(f"duplicate skinId: {sid}")
        by_id[sid] = s

    case_ids = set()
    for c in cases:
        cid = c.get("caseId")
        if not cid:
            errors.append("a case entry is missing caseId")
            continue
        if cid in case_ids:
            errors.append(f"duplicate caseId: {cid}")
        case_ids.add(cid)

        enabled = bool(c.get("enabled"))
        if enabled:
            missing = [f for f in CASE_FIELDS if f not in c]
            if missing:
                errors.append(f"case '{cid}' is enabled but missing fields: {missing}")

        pool = c.get("manualDropPool") or []
        seen = set()
        for raw in pool:
            try:
                pid, _ = pool_skin_id(raw)
            except ValueError as e:
                errors.append(f"case '{cid}': {e}")
                continue
            if pid in seen:
                warnings.append(f"case '{cid}' lists skinId '{pid}' more than once; it will be collapsed")
            seen.add(pid)
            target = by_id.get(pid)
            if target is None:
                errors.append(f"case '{cid}' references unknown skinId '{pid}'")
            elif enabled and not bool(target.get("enabled")):
                errors.append(f"enabled case '{cid}' references disabled skin '{pid}'")
        if enabled and not seen:
            errors.append(f"enabled case '{cid}' has an empty drop pool")

        rkey = c.get("resourceKey")
        if rkey:
            png = art_dir / (Path(rkey).name + ".png")
            if not art_dir.exists():
                warnings.append(f"art folder not found, skipped PNG check for '{cid}': {art_dir}")
            elif not png.exists():
                warnings.append(f"case '{cid}' PNG not found for resourceKey '{rkey}': expected {png.name}")

    return errors, warnings


def next_version():
    versions = [
        int(m.group(1))
        for f in MIGRATION_DIR.glob("V*__*.sql")
        if (m := re.match(r"V(\d+)__", f.name))
    ]
    return (max(versions) + 1) if versions else 1


def build_sql(skins, cases, version, cases_only=False):
    lines = []
    add = lines.append
    add("-- ============================================================================")
    add(f"-- V{version} - Catalog sync (generated from Unity skins.json + cases.json)")
    add("-- ============================================================================")
    if cases_only:
        add("-- Cases-only sync: upserts cases and rebuilds their drop pools and rarity")
        add("-- weights. Skins (and their vp_value) are left untouched. Touches catalog")
        add("-- tables only; never deletes players, inventory, wallets, or history.")
        add("-- Generated by tools/catalog/generate_catalog_migration.py --cases-only.")
    else:
        add("-- Upserts all skins and cases and rebuilds the drop pools of the cases below.")
        add("-- Touches catalog tables only; never deletes players, inventory, wallets, or")
        add("-- history. Generated by tools/catalog/generate_catalog_migration.py.")
    add("-- ============================================================================")
    add("")
    if not cases_only:
        add(f"-- Skins ({len(skins)}). Upsert by primary key id.")
        add("INSERT INTO skins (id, display_name, weapon, rarity, vp_value, image_ref, active) VALUES")
        add(",\n".join(
            f"    ({sql_str(s['skinId'])}, {sql_str(s.get('displayName',''))}, {sql_str(s.get('weapon',''))}, "
            f"{sql_str(s.get('rarity',''))}, {int(s.get('vpValue',0))}, {sql_str(s.get('resourceKey',''))}, "
            f"{sql_bool(s.get('enabled'))})"
            for s in skins))
        add("ON CONFLICT (id) DO UPDATE SET")
        add("    display_name = EXCLUDED.display_name,")
        add("    weapon       = EXCLUDED.weapon,")
        add("    rarity       = EXCLUDED.rarity,")
        add("    vp_value     = EXCLUDED.vp_value,")
        add("    image_ref    = EXCLUDED.image_ref,")
        add("    active       = EXCLUDED.active;")
        add("")
    add(f"-- Cases ({len(cases)}). Upsert by primary key id.")
    add("INSERT INTO case_definitions (id, display_name, price_vp, image_ref, active) VALUES")
    add(",\n".join(
        f"    ({sql_str(c['caseId'])}, {sql_str(c.get('displayName',''))}, {int(c.get('price',0))}, "
        f"{sql_str(c.get('resourceKey',''))}, {sql_bool(c.get('enabled'))})"
        for c in cases))
    add("ON CONFLICT (id) DO UPDATE SET")
    add("    display_name = EXCLUDED.display_name,")
    add("    price_vp     = EXCLUDED.price_vp,")
    add("    image_ref    = EXCLUDED.image_ref,")
    add("    active       = EXCLUDED.active;")
    add("")
    add("-- Rebuild the drop pools of the cases in this sync only. Nothing references")
    add("-- case_entries, so deleting and reinserting them is safe.")
    add(f"DELETE FROM case_entries WHERE case_id IN ({', '.join(sql_str(c['caseId']) for c in cases)});")
    add("")
    rows = []
    for c in cases:
        for raw in (c.get("manualDropPool") or []):
            pid, weight = pool_skin_id(raw)
            rows.append((c["caseId"], pid, weight))
    seen = set()
    deduped = []
    for cid, pid, weight in rows:
        if (cid, pid) in seen:
            continue
        seen.add((cid, pid))
        deduped.append((cid, pid, weight))
    add(f"-- Drop-pool entries ({len(deduped)}).")
    add("INSERT INTO case_entries (id, case_id, skin_id, weight) VALUES")
    add(",\n".join(
        f"    (gen_random_uuid(), {sql_str(cid)}, {sql_str(pid)}, {weight})"
        for cid, pid, weight in deduped) + ";")
    add("")

    weight_rows = []
    weight_seen = set()
    for c in cases:
        for rw in (c.get("rarityWeights") or []):
            rarity = (rw.get("rarity") or "").strip()
            if not rarity:
                continue
            key = (c["caseId"], rarity)
            if key in weight_seen:
                continue
            weight_seen.add(key)
            weight_rows.append((c["caseId"], rarity, float(rw.get("weight", 0))))
    add("-- Rebuild authored rarity weights (rarity-first roll odds) for these cases.")
    add(f"DELETE FROM case_rarity_weights WHERE case_id IN ({', '.join(sql_str(c['caseId']) for c in cases)});")
    if weight_rows:
        add(f"-- Rarity weights ({len(weight_rows)}).")
        add("INSERT INTO case_rarity_weights (id, case_id, rarity, weight) VALUES")
        add(",\n".join(
            f"    (gen_random_uuid(), {sql_str(cid)}, {sql_str(rarity)}, {weight:g})"
            for cid, rarity, weight in weight_rows) + ";")
        add("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate the next Flyway catalog-sync migration.")
    parser.add_argument("--dry-run", action="store_true",
                        help="validate and print the SQL that would be written; write no files")
    parser.add_argument("--cases-only", action="store_true",
                        help="emit only cases, drop pools, and rarity weights; leave skins (and vp_value) untouched")
    parser.add_argument("--skins-json", type=Path, default=DEFAULT_SKINS)
    parser.add_argument("--cases-json", type=Path, default=DEFAULT_CASES)
    parser.add_argument("--art-cases-dir", type=Path, default=DEFAULT_ART_CASES)
    args = parser.parse_args()

    try:
        skins = load_array(args.skins_json, "skins")
        cases = load_array(args.cases_json, "cases")
    except (OSError, ValueError, json.JSONDecodeError) as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 2

    errors, warnings = validate(skins, cases, args.art_cases_dir)
    for w in warnings:
        print(f"WARNING: {w}")
    if errors:
        print(f"\nVALIDATION FAILED ({len(errors)} error(s)):", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        return 1

    version = next_version()
    sql = build_sql(skins, cases, version, cases_only=args.cases_only)
    out = MIGRATION_DIR / f"V{version}__catalog_sync.sql"

    print(f"\nValidation passed: {len(skins)} skins, {len(cases)} cases.")
    if args.dry_run:
        print(f"DRY RUN: would write {out.relative_to(REPO_ROOT)}\n")
        print(sql)
        return 0

    out.write_text(sql, encoding="utf-8", newline="\n")
    print(f"Wrote {out.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
